services:
    _defaults:
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        autowire: true
        autoconfigure: true
        public: true
    
    # Repositories
    HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnBroadcastRepository: ~
    hpo_espn_api_symfony_bundle.repository.espn_broadcast: '@HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnBroadcastRepository'
    
    HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnCompetitionRepository: ~
    hpo_espn_api_symfony_bundle.repository.espn_competition: '@HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnCompetitionRepository'
    
    HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnCompetitorRepository: ~
    hpo_espn_api_symfony_bundle.repository.espn_competitor: '@HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnCompetitorRepository'
    
    HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnFranchiseRepository: ~
    hpo_espn_api_symfony_bundle.repository.espn_franchise: '@HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnFranchiseRepository'
    
    HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnImageRepository: ~
    hpo_espn_api_symfony_bundle.repository.espn_image: '@HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnImageRepository'
    
    HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnScheduleEventRepository: ~
    hpo_espn_api_symfony_bundle.repository.espn_schedule_event: '@HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnScheduleEventRepository'
    
    HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnScheduleRepository: ~
    hpo_espn_api_symfony_bundle.repository.espn_schedule: '@HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnScheduleRepository'
    
    HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnSeasonRepository: ~
    hpo_espn_api_symfony_bundle.repository.espn_season: '@HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnSeasonRepository'
    
    HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnSeasonTeamRepository: ~
    hpo_espn_api_symfony_bundle.repository.espn_season_team: '@HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnSeasonTeamRepository'
    
    HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnSeasonTypeGroupRepository: ~
    hpo_espn_api_symfony_bundle.repository.espn_season_type_group: '@HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnSeasonTypeGroupRepository'
    
    HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnSeasonTypeRepository: ~
    hpo_espn_api_symfony_bundle.repository.espn_season_type: '@HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnSeasonTypeRepository'
    
    HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnSeasonTypeTeamRecordRepository: ~
    hpo_espn_api_symfony_bundle.repository.espn_season_type_team_record: '@HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnSeasonTypeTeamRecordRepository'
    
    HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnSeasonTypeTeamRecordStatRepository: ~
    hpo_espn_api_symfony_bundle.repository.espn_season_type_team_record_stat: '@HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnSeasonTypeTeamRecordStatRepository'
    
    HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnSeasonTypeWeekRepository: ~
    hpo_espn_api_symfony_bundle.repository.espn_season_type_week: '@HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnSeasonTypeWeekRepository'
    
    HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnVenueRepository: ~
    hpo_espn_api_symfony_bundle.repository.espn_venue: '@HansPeterOrding\EspnApiSymfonyBundle\Repository\EspnVenueRepository'
    
    # Converters
    HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnBroadcastConverter: ~
    hpo_espn_api_symfony_bundle.converter.espn_broadcast: '@HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnBroadcastConverter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnCompetitionStatusConverter: ~
    hpo_espn_api_symfony_bundle.converter.espn_competition_status: '@HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnCompetitionStatusConverter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnCompetitionStatusTypeConverter: ~
    hpo_espn_api_symfony_bundle.converter.espn_competition_status_type: '@HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnCompetitionStatusTypeConverter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnCompetitorScoreConverter: ~
    hpo_espn_api_symfony_bundle.converter.espn_competitor_score: '@HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnCompetitorScoreConverter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnImageConverter: ~
    hpo_espn_api_symfony_bundle.converter.espn_image: '@HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnImageConverter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnLinkConverter: ~
    hpo_espn_api_symfony_bundle.converter.espn_link: '@HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnLinkConverter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnNoteConverter: ~
    hpo_espn_api_symfony_bundle.converter.espn_note: '@HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnNoteConverter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnVenueAddressConverter: ~
    hpo_espn_api_symfony_bundle.converter.espn_venue_address: '@HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnVenueAddressConverter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnWeekConverter: ~
    hpo_espn_api_symfony_bundle.converter.espn_week: '@HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnWeekConverter'
    
    # Dependent converters
    HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnCompetitionConverter:
        arguments:
            $espnCompetitionRepository: '@hpo_espn_api_symfony_bundle.repository.espn_competition'
            $espnVenueRepository: '@hpo_espn_api_symfony_bundle.repository.espn_venue'
            $espnCompetitorConverter: '@hpo_espn_api_symfony_bundle.converter.espn_competitor'
            $espnNoteConverter: '@hpo_espn_api_symfony_bundle.converter.espn_note'
            $espnBroadcastConverter: '@hpo_espn_api_symfony_bundle.converter.espn_broadcast'
            $espnCompetitionStatusConverter: '@hpo_espn_api_symfony_bundle.converter.espn_competition_status'
    hpo_espn_api_symfony_bundle.converter.espn_competition: '@HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnCompetitionConverter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnCompetitorConverter:
        arguments:
            $espnCompetitorRepository: '@hpo_espn_api_symfony_bundle.repository.espn_competitor'
            $espnTeamRepository: '@hpo_espn_api_symfony_bundle.repository.espn_season_team'
            $espnCompetitorScoreConverter: '@hpo_espn_api_symfony_bundle.converter.espn_competitor_score'
    hpo_espn_api_symfony_bundle.converter.espn_competitor: '@HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnCompetitorConverter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnFranchiseConverter:
        arguments:
            $espnFranchiseRepository: '@hpo_espn_api_symfony_bundle.repository.espn_franchise'
            $espnVenueConverter: '@hpo_espn_api_symfony_bundle.converter.espn_venue'
    hpo_espn_api_symfony_bundle.converter.espn_franchise: '@HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnFranchiseConverter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnScheduleConverter:
        arguments:
            $espnScheduleRepository: '@hpo_espn_api_symfony_bundle.repository.espn_schedule'
            $espnSeasonConverter: '@hpo_espn_api_symfony_bundle.converter.espn_season'
            $espnScheduleEventConverter: '@hpo_espn_api_symfony_bundle.converter.espn_schedule_event'
    hpo_espn_api_symfony_bundle.converter.espn_schedule: '@HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnScheduleConverter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnScheduleEventConverter:
        arguments:
            $espnScheduleEventRepository: '@hpo_espn_api_symfony_bundle.repository.espn_schedule_event'
            $espnWeekConverter: '@hpo_espn_api_symfony_bundle.converter.espn_week'
            $espnCompetitionConverter: '@hpo_espn_api_symfony_bundle.converter.espn_competition'
    hpo_espn_api_symfony_bundle.converter.espn_schedule_event: '@HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnScheduleEventConverter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnSeasonConverter:
        arguments:
            $espnSeasonRepository: '@hpo_espn_api_symfony_bundle.repository.espn_season'
    hpo_espn_api_symfony_bundle.converter.espn_season: '@HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnSeasonConverter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnSeasonTeamConverter:
        arguments:
            $espnSeasonTeamRepository: '@hpo_espn_api_symfony_bundle.repository.espn_season_team'
            $imageConverter: '@hpo_espn_api_symfony_bundle.converter.espn_image'
            $linkConverter: '@hpo_espn_api_symfony_bundle.converter.espn_link'
    hpo_espn_api_symfony_bundle.converter.espn_season_team: '@HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnSeasonTeamConverter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnSeasonTypeConverter:
        arguments:
            $espnSeasonTypeRepository: '@hpo_espn_api_symfony_bundle.repository.espn_season_type'
    hpo_espn_api_symfony_bundle.converter.espn_season_type: '@HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnSeasonTypeConverter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnSeasonTypeGroupConverter:
        arguments:
            $espnSeasonTypeGroupRepository: '@hpo_espn_api_symfony_bundle.repository.espn_season_type_group'
    hpo_espn_api_symfony_bundle.converter.espn_season_type_group: '@HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnSeasonTypeGroupConverter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnSeasonTypeTeamRecordConverter:
        arguments:
            $espnSeasonTypeTeamRecordRepository: '@hpo_espn_api_symfony_bundle.repository.espn_season_type_team_record'
            $statConverter: '@hpo_espn_api_symfony_bundle.converter.espn_season_type_team_record_stat'
    hpo_espn_api_symfony_bundle.converter.espn_season_type_team_record: '@HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnSeasonTypeTeamRecordConverter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnSeasonTypeTeamRecordStatConverter:
        arguments:
            $espnSeasonTypeTeamRecordStatRepository: '@hpo_espn_api_symfony_bundle.repository.espn_season_type_team_record_stat'
    hpo_espn_api_symfony_bundle.converter.espn_season_type_team_record_stat: '@HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnSeasonTypeTeamRecordStatConverter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnSeasonTypeWeekConverter:
        arguments:
            $espnSeasonTypeWeekRepository: '@hpo_espn_api_symfony_bundle.repository.espn_season_type_week'
    hpo_espn_api_symfony_bundle.converter.espn_season_type_week: '@HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnSeasonTypeWeekConverter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnVenueConverter:
        arguments:
            $espnVenueRepository: '@hpo_espn_api_symfony_bundle.repository.espn_venue'
            $venueAddressConverter: '@hpo_espn_api_symfony_bundle.converter.espn_venue_address'
    hpo_espn_api_symfony_bundle.converter.espn_venue: '@HansPeterOrding\EspnApiSymfonyBundle\Converter\EspnVenueConverter'
    
    # Importer
    HansPeterOrding\EspnApiSymfonyBundle\Importer\EspnScheduleImporter:
        arguments:
            $converter: '@hpo_espn_api_symfony_bundle.converter.espn_schedule'
    hpo_espn_api_symfony_bundle.importer.espn_schedule: '@HansPeterOrding\EspnApiSymfonyBundle\Importer\EspnScheduleImporter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Importer\EspnSeasonImporter:
        arguments:
            $converter: '@hpo_espn_api_symfony_bundle.converter.espn_season'
    hpo_espn_api_symfony_bundle.importer.espn_season: '@HansPeterOrding\EspnApiSymfonyBundle\Importer\EspnSeasonImporter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Importer\EspnSeasonTeamImporter:
        arguments:
            $converter: '@hpo_espn_api_symfony_bundle.converter.espn_season_team'
    hpo_espn_api_symfony_bundle.importer.espn_season_team: '@HansPeterOrding\EspnApiSymfonyBundle\Importer\EspnSeasonTeamImporter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Importer\EspnSeasonTypeGroupImporter:
        arguments:
            $converter: '@hpo_espn_api_symfony_bundle.converter.espn_season_type_group'
    hpo_espn_api_symfony_bundle.importer.espn_season_type_group: '@HansPeterOrding\EspnApiSymfonyBundle\Importer\EspnSeasonTypeGroupImporter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Importer\EspnSeasonTypeImporter:
        arguments:
            $converter: '@hpo_espn_api_symfony_bundle.converter.espn_season_type'
    hpo_espn_api_symfony_bundle.importer.espn_season_type: '@HansPeterOrding\EspnApiSymfonyBundle\Importer\EspnSeasonTypeImporter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Importer\EspnSeasonTypeTeamRecordImporter:
        arguments:
            $converter: '@hpo_espn_api_symfony_bundle.converter.espn_season_type_team_record'
    hpo_espn_api_symfony_bundle.importer.espn_season_type_team_record: '@HansPeterOrding\EspnApiSymfonyBundle\Importer\EspnSeasonTypeTeamRecordImporter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Importer\EspnSeasonTypeWeekImporter:
        arguments:
            $converter: '@hpo_espn_api_symfony_bundle.converter.espn_season_type_week'
    hpo_espn_api_symfony_bundle.importer.espn_season_type_week: '@HansPeterOrding\EspnApiSymfonyBundle\Importer\EspnSeasonTypeWeekImporter'
    
    HansPeterOrding\EspnApiSymfonyBundle\Importer\EspnVenueImporter:
        arguments:
            $converter: '@hpo_espn_api_symfony_bundle.converter.espn_venue'
    hpo_espn_api_symfony_bundle.importer.espn_venue: '@HansPeterOrding\EspnApiSymfonyBundle\Importer\EspnVenueImporter'
    
    # Services 
    HansPeterOrding\EspnApiSymfonyBundle\Service\SeasonImportService: ~
    HansPeterOrding\EspnApiSymfonyBundle\Service\SeasonTeamImportService: ~
    HansPeterOrding\EspnApiSymfonyBundle\MessageHandler\EspnSync\SyncEspnScheduleHandler: ~
    HansPeterOrding\EspnApiSymfonyBundle\MessageHandler\EspnSync\SyncEspnTeamHandler: ~
    HansPeterOrding\EspnApiSymfonyBundle\MessageHandler\EspnSync\SyncEspnVenueHandler: ~
